config/routes.rb
Videoclub::Application.routes.draw do
   match "mycomments" => "users#mycomments"
   match "myrents" => "users#myrents"
   match "search" => "films#finder"

  resources :commercials

   authenticated :user do
      root :to =>"home#index"
   end

   root :to =>"home#index"
   devise_for :users

   resources :users, :only => [:index, :destroy] do
      resources :rents, :only => [:index]
      resources :comments, :only => [:index]
   end

   resources :films do
      resources :comments
      resources :rents, :only => [:index, :create, :new]
   end

   resources :comments, :only => [:edit, :destroy]
   resources :rents, :except => [:create, :new]
   resources :groups

   resources :paypals
   resources :cards

end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :comments
  has_many :rents
  has_many :films, :through => :rents
  has_many :cards, :dependent => :destroy
  has_many :suscriptions, :dependent => :destroy
  has_many :groups, :through => :suscriptions
  before_create :asigna_grupo_defecto

  attr_accessor :login
  validates_presence_of :username
  validates_uniqueness_of :username
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :authentication_keys => [:login]

  # Setup accessible (or protected) attributes for your model
  attr_accessible :username,:email, :password, :password_confirmation, :remember_me, :login
  # attr_accessible :title, :body


 def self.find_first_by_auth_conditions(warden_conditions)
    conditions = warden_conditions.dup
    if login = conditions.delete(:login)
      where(conditions).where(["lower(username) = :value OR lower(email) = :value", { :value => login.downcase }]).first
    else
      where(conditions).first
    end
  end
 def asigna_grupo_defecto
	self.groups << Group.find_by_name('base')
 end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :authenticate_user!
  before_filter :is_admin, :except => [:mycomments, :myrents]
  def index
      @users = User.all
  end

  def show
      @user = User.find(params[:id])
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_comentario.html.erb
<h1>Mis comentarios</h1>

<table>
  <tr>
    <th>Comentario</th>
    <th>Película</th>
    <th></th>
  </tr>

<% @user.comments.each do |c| %>
  <tr>
    <td><%= c.comentario %></td>
    <td><%= c.film.title %></td>
    <td><%= link_to 'Show', c.film %></td>
  </tr>
<% end %>
</table>
<br />

app/views/users/_form.html.haml
= form_for @user, :html => { :class => 'form-horizontal' } do |f|
  .control-group
    = f.label :email, :class => 'control-label'
    .controls
      = f.text_field :email, :class => 'text_field'
  .control-group
    = f.label :encrypted_password, :class => 'control-label'
    .controls
      = f.text_field :encrypted_password, :class => 'text_field'
  .control-group
    = f.label :reset_password_token, :class => 'control-label'
    .controls
      = f.text_field :reset_password_token, :class => 'text_field'
  .control-group
    = f.label :reset_password_sent_at, :class => 'control-label'
    .controls
      = f.datetime_select :reset_password_sent_at, :class => 'datetime_select'
  .control-group
    = f.label :remember_created_at, :class => 'control-label'
    .controls
      = f.datetime_select :remember_created_at, :class => 'datetime_select'
  .control-group
    = f.label :sign_in_count, :class => 'control-label'
    .controls
      = f.number_field :sign_in_count, :class => 'number_field'
  .control-group
    = f.label :current_sign_in_at, :class => 'control-label'
    .controls
      = f.datetime_select :current_sign_in_at, :class => 'datetime_select'
  .control-group
    = f.label :last_sign_in_at, :class => 'control-label'
    .controls
      = f.datetime_select :last_sign_in_at, :class => 'datetime_select'
  .control-group
    = f.label :current_sign_in_ip, :class => 'control-label'
    .controls
      = f.text_field :current_sign_in_ip, :class => 'text_field'
  .control-group
    = f.label :last_sign_in_ip, :class => 'control-label'
    .controls
      = f.text_field :last_sign_in_ip, :class => 'text_field'
  .control-group
    = f.label :username, :class => 'control-label'
    .controls
      = f.text_field :username, :class => 'text_field'
  .form-actions
    = f.submit nil, :class => 'btn btn-primary'
    = link_to t('.cancel', :default => t("helpers.links.cancel")), users_path, :class => 'btn'

app/views/users/_tarjetas.html.erb
<h1>Mis tarjetas de crédito</h1>

<table class="tabla" style="width: 100%">
  <tr>
    <th>Nº de tarjeta</th>
    <th>Fecha de caducidad</th>
    <th>Codigo de seguridad</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @user.cards.each do |card| %>
  <tr>
    <td><%= card.n_cuenta %></td>
    <td><%= time_tag card.fecha %></td>
    <td><%= card.secure_code %></td>
    <td class="btn-tabla"><%= link_to 'Mostrar', card, :class => "btn btn-mini btn-blue"%></td>
    <td class="btn-tabla"><%= link_to 'Editar', edit_card_path(card), :class => "btn btn-mini btn-blue" %></td>
    <td class="btn-tabla"><%= link_to 'Eliminar', card, confirm: '¿Eliminar datos de la tarjeta?', method: :delete, :class => "btn btn-mini btn-blue" %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'Añadir Tarjeta', new_card_path, :class => "btn btn-mini btn-blue" %>

app/views/users/edit.html.haml
- model_class = @user.class
.page-header
  %h1=t '.title', :default => t('helpers.titles.edit', :model => model_class.model_name.human, :default => "Edit #{model_class.model_name.human}")
= render :partial => "form"

app/views/users/index.html.erb
<h1>Gestión de Usuarios</h1>

<table class="tabla">
  <tr>
    <th>Nombre de Usuario</th>
    <th>Email</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @users.each do |user| %>
  <tr>
    <td><%= user.username %></td>
    <td><%= user.email %></td>
    <td class="btn-tabla"><%= link_to 'Alquileres/Compras', user_rents_path(user.id), :class => 'btn btn-mini btn-blue' %></td>
    <td class="btn-tabla"><%= link_to 'Comentarios', user_comments_path(user.id), :class => 'btn btn-mini btn-blue' %></td>
    <td class="btn-tabla"><%= link_to 'Eliminar', user, confirm: 'Are you sure?', method: :delete, :class => 'btn btn-mini btn-blue' %></td>
  </tr>
<% end %>
</table>

<br />

app/views/users/index.html.haml
- model_class = User.new.class
.page-header
  %h1=t '.title', :default => model_class.model_name.human.pluralize
%table.table.table-striped
  %thead
    %tr
      %th= model_class.human_attribute_name(:id)
      %th= model_class.human_attribute_name(:email)
      %th= model_class.human_attribute_name(:encrypted_password)
      %th= model_class.human_attribute_name(:reset_password_token)
      %th= model_class.human_attribute_name(:reset_password_sent_at)
      %th= model_class.human_attribute_name(:remember_created_at)
      %th= model_class.human_attribute_name(:sign_in_count)
      %th= model_class.human_attribute_name(:current_sign_in_at)
      %th= model_class.human_attribute_name(:last_sign_in_at)
      %th= model_class.human_attribute_name(:current_sign_in_ip)
      %th= model_class.human_attribute_name(:last_sign_in_ip)
      %th= model_class.human_attribute_name(:username)
      %th= model_class.human_attribute_name(:created_at)
      %th=t '.actions', :default => t("helpers.actions")
  %tbody
    - @users.each do |user|
      %tr
        %td= link_to user.id, user_path(user)
        %td= user.email
        %td= user.encrypted_password
        %td= user.reset_password_token
        %td= user.reset_password_sent_at
        %td= user.remember_created_at
        %td= user.sign_in_count
        %td= user.current_sign_in_at
        %td= user.last_sign_in_at
        %td= user.current_sign_in_ip
        %td= user.last_sign_in_ip
        %td= user.username
        %td=l user.created_at
        %td
          = link_to t('.edit', :default => t("helpers.links.edit")), edit_user_path(user), :class => 'btn btn-mini'
          = link_to t('.destroy', :default => t("helpers.links.destroy")), user_path(user), :method => :delete, :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')), :class => 'btn btn-mini btn-danger'

= link_to t('.new', :default => t("helpers.links.new")), new_user_path, :class => 'btn btn-primary'

app/views/users/mycomments.html.haml
.page-header
  = link_to edit_user_registration_path, :class => 'btn btn-primary' do
    %i.icon-plus.icon-white
    Back

  %h1 Mis Comentarios

%table.tabla
  %thead
    %tr
      %th.first Película
      %th Comentario
      %th
      %th
      %th
  %tbody
    - current_user.comments.each do |c|
      %tr
        %td.title-film
          = link_to c.film.title, c.film
        %td
          = c.comentario
        %td.link
          = link_to 'Ver', c.film, :class => "btn btm-mini btn-blue"
        %td.link
          = link_to 'Editar', edit_comment_path(c), :class => "btn btm-mini btn-blue"
        %td.link
          = link_to 'Eliminar', comment_path(c), confirm: '¿Seguro?', method: :delete, :class => "btn btm-mini btn-blue"

app/views/users/myrents.html.haml
.page-header
  = link_to edit_user_registration_path, :class => 'btn btn-primary' do
    %i.icon-plus.icon-white
    Back

  %h1 Mis Alquileres

%table.tabla
  %thead
    %tr
      %th Película
      %th Fecha de Inicio
      %th Fecha de Final
  %tbody
    - current_user.rents.each do |r|
      %tr
        %td= link_to r.film.title, r.film
        %td= time_tag r.start_date
        %td= time_tag r.end_date

app/views/users/new.html.haml
- model_class = @user.class
.page-header
  %h1=t '.title', :default => t('helpers.titles.new', :model => model_class.model_name.human, :default => "New #{model_class.model_name.human}")
= render :partial => "form"

app/views/users/show.html.erb
<p>Email: <%= @user.email if @user.email %></p>

app/views/users/show.html.haml
- model_class = @user.class
.page-header
  %h1=t '.title', :default => model_class.model_name.human

%p
  %strong= model_class.human_attribute_name(:email) + ':'
  %br
  = @user.email
%p
  %strong= model_class.human_attribute_name(:encrypted_password) + ':'
  %br
  = @user.encrypted_password
%p
  %strong= model_class.human_attribute_name(:reset_password_token) + ':'
  %br
  = @user.reset_password_token
%p
  %strong= model_class.human_attribute_name(:reset_password_sent_at) + ':'
  %br
  = @user.reset_password_sent_at
%p
  %strong= model_class.human_attribute_name(:remember_created_at) + ':'
  %br
  = @user.remember_created_at
%p
  %strong= model_class.human_attribute_name(:sign_in_count) + ':'
  %br
  = @user.sign_in_count
%p
  %strong= model_class.human_attribute_name(:current_sign_in_at) + ':'
  %br
  = @user.current_sign_in_at
%p
  %strong= model_class.human_attribute_name(:last_sign_in_at) + ':'
  %br
  = @user.last_sign_in_at
%p
  %strong= model_class.human_attribute_name(:current_sign_in_ip) + ':'
  %br
  = @user.current_sign_in_ip
%p
  %strong= model_class.human_attribute_name(:last_sign_in_ip) + ':'
  %br
  = @user.last_sign_in_ip
%p
  %strong= model_class.human_attribute_name(:username) + ':'
  %br
  = @user.username

.form-actions
  = link_to t('.back', :default => t("helpers.links.back")), users_path, :class => 'btn'
  = link_to t('.edit', :default => t("helpers.links.edit")), edit_user_path(@user), :class => 'btn'
  = link_to t('.destroy', :default => t("helpers.links.destroy")), user_path(@user), :method => "delete", :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')), :class => 'btn btn-danger'

app/views/users/tarjetas.html.erb
<h1>Mis tarjetas de crédito</h1>

<table>
  <tr>
    <th>Nº de tarjeta</th>
    <th>Fecha de caducidad</th>
    <th>Codigo de seguridad</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @user.cards.each do |card| %>
  <tr>
    <td><%= card.n_cuenta %></td>
    <td><%= card.fecha %></td>
    <td><%= card.secure_code %></td>
    <td><%= link_to 'Show', card %></td>
    <td><%= link_to 'Edit', edit_card_path(film) %></td>
    <td><%= link_to 'Destroy', card, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Card>', new_card_path %>