config/routes.rb
Videoclub::Application.routes.draw do
   match "mycomments" => "users#mycomments"
   match "myrents" => "users#myrents"
   match "search" => "films#finder"

  resources :commercials

   authenticated :user do
      root :to =>"home#index"
   end

   root :to =>"home#index"
   devise_for :users

   resources :users, :only => [:index, :destroy] do
      resources :rents, :only => [:index]
      resources :comments, :only => [:index]
   end

   resources :films do
      resources :comments
      resources :rents, :only => [:index, :create, :new]
   end

   resources :comments, :only => [:edit, :destroy]
   resources :rents, :except => [:create, :new]
   resources :groups

   resources :paypals
   resources :cards

end

app/models/film.rb
class Film < ActiveRecord::Base
  has_many :comments, :dependent => :destroy
  has_many :rents
  has_many :users, :through => :rents

  attr_accessible :buy_price, :rental_price, :sinopsis, :time, :title, :poster, :movie, :year
  has_attached_file :poster #, :styles => { :medium => "214x317>", :thumb => "107x159>" }
  has_attached_file :movie
  validates_presence_of :title
  validates_presence_of :rental_price
  validates_presence_of :buy_price
  validates_attachment_presence :poster
  validates_attachment_presence :movie
  validates_uniqueness_of :title
  validates :time, :numericality => { :only_integer => true, :greater_than => 0 }
  validates :year, :numericality => { :only_integer => true, :greater_than => 1800, :less_than => 2099 }



 def self.search(search)
    if search
       find(:all, :conditions => ['title LIKE ?', "%#{search}%"])
    else
       find(:all)
    end
 end


end

app/controllers/films_controller.rb
class FilmsController < ApplicationController
  before_filter :is_admin, :except => [:show, :finder, :result]
  # GET /films
  # GET /films.json
  def index
    @films = Film.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @films }
    end
  end

  # GET /films/1
  # GET /films/1.json
  def show
    @film = Film.find(params[:id])
    @commercials = Commercial.all(:order => 'RANDOM()') #, :limit => 2)

    if @film
        @comment = @film.comments.build
        @rent = @film.rents.build
    end
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @film }
    end
  end

  # GET /films/new
  # GET /films/new.json
  def new
    @film = Film.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @film }
    end
  end

  # GET /films/1/edit
  def edit
    @film = Film.find(params[:id])
  end

  # POST /films
  # POST /films.json
  def create
    @film = Film.new(params[:film])

    respond_to do |format|
      if @film.save
        format.html { redirect_to @film, notice: 'Film was successfully created.' }
        format.json { render json: @film, status: :created, location: @film }
      else
        format.html { render action: "new" }
        format.json { render json: @film.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /films/1
  # PUT /films/1.json
  def update
    @film = Film.find(params[:id])

    respond_to do |format|
      if @film.update_attributes(params[:film])
        format.html { redirect_to @film, notice: 'Film was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @film.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /films/1
  # DELETE /films/1.json
  def destroy
    @film = Film.find(params[:id])
    @film.destroy

    respond_to do |format|
      format.html { redirect_to films_url }
      format.json { head :no_content }
    end
  end
  def finder
     @search = Film.search(params[:search])

     respond_to do |format|
         format.html # result.html.erb
         format.xml  { render :xml => @noticias }
     end
  end
end

app/helpers/films_helper.rb
module FilmsHelper
end

app/views/films/_alquilada.html.erb
<%= form_for ([@film, @rent]) do |f| %>
  <%= f.submit :class => 'btn btn-large btn-danger btnPurchase', :style => "width: 140px", :value => "Comprar: "+@film.buy_price.to_s+"€"%>
<%end%>
<p class="alquilado">Alquilada hasta: <%=time_tag @film.rents.find_by_user_id(current_user.id).end_date %></p>

app/views/films/_comprada.html.erb
<p class="alquilado comprado"> ¡¡Película Comprada!! </p>

app/views/films/_film_con_anuncion.html.erb
<p><%= video_tag @film.movie.url, :size => "520x400", :controls => true, :id =>'pelicula' %></p>
<p><%= video_tag @film.movie.url, :size => "520x400", :controls => false, :id =>'anuncio' %></p>
<input type="text" id="FilmOrigin" style="display:none;" value=<%= @film.movie.url %> />
<% @commercials.each do |c| %>
   <input type="text" class="Commercials" style="display:none;" value=<%= c.file.url %> />
<% end %>
<script type="text/javascript">
  Commercials = document.getElementsByClassName("Commercials");
  NumElem = Commercials.length;
  v = document.getElementById("pelicula");
  a = document.getElementById("anuncio");

  v.addEventListener('play',  vPlay,  false);
  v.addEventListener('pause', vPause, false);
  a.addEventListener('ended', aEnded, false);
  v.addEventListener('ended', vEnded, false);
</script>

app/views/films/_film_sin_anuncios.html.erb
<p><%= video_tag @film.movie.url, :size => "520x400", :controls => true  %></p>

app/views/films/_form.html.erb
<%= form_for(@film) do |f| %>
  <% if @film.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@film.errors.count, "error") %> prohibited this film from being saved:</h2>

      <ul>
      <% @film.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :year %><br />
    <%= f.text_field :year %>
  </div>
  <div class="field">
    <%= f.label :time %><br />
    <%= f.number_field :time %>
  </div>
  <div class="field">
    <%= f.label :rental_price %><br />
    <%= f.text_field :rental_price %>
  </div>
  <div class="field">
    <%= f.label :buy_price %><br />
    <%= f.text_field :buy_price %>
  </div>
  <div class="field">
    <%= f.label :sinopsis %><br />
    <%= f.text_area :sinopsis %>
  </div>
  <div class="field">
    <%= f.label :poster %><br />
    <%= f.file_field :poster %>
  </div>
  <div class="field">
    <%= f.label :movie %><br />
    <%= f.file_field :movie %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>

<% end %>

app/views/films/_sincomprar.html.erb
<% if current_user %>
  <%= form_for ([@film, @rent]) do |f| %>
    <%= f.submit :class => 'btn btn-large btn-danger btnPurchase', :style => "width: 140px", :value => "Comprar: "+@film.buy_price.to_s+"€"%>
  <%end%>
  <%= form_for ([@film, @rent]) do |f| %>
    <%= f.submit :class => 'btn btn-large btn-danger btnPurchase', :style => "width: 140px", :value => "Alquilar: "+@film.rental_price.to_s+"€"%>
  <%end%>
<% else %>
   <p class="alquilado comprado">Logueate para alquilar o comprar la película</p>
<% end %>

app/views/films/edit.html.erb
<h1>Editing film</h1>

<%= render 'form' %>

<%= link_to 'Show', @film %> |
<%= link_to 'Back', films_path %>

app/views/films/finder.html.erb
<table class="tabla" style="margin-top: 20px; width: 100%">
  <tr>
    <th>Poster</th>
    <th>Titulo</th>
    <th>Sinopsis</th>
  </tr>

<%@search.each do |r|%>
  <tr>
    <td><%= image_tag r.poster.url, :size => "70x40"%></td>
    <td><%= link_to r.title, r %></td>
    <td><%= r.sinopsis %></td>
  </tr>
<%end%>

</table>

app/views/films/gallery.html.erb
<h1>Listing films</h1>

<table>
  <tr>
    <th>Title</th>
    <th>Time</th>
    <th>Rental price</th>
    <th>Buy price</th>
    <th>Sinopsis</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @films.each do |film| %>
  <tr>
    <td><%= film.title %></td>
    <td><%= film.time %></td>
    <td><%= film.rental_price %></td>
    <td><%= film.buy_price %></td>
    <td><%= film.sinopsis %></td>
    <td><%= link_to 'Show', film %></td>
    <td><%= link_to 'Edit', edit_film_path(film) %></td>
    <td><%= link_to 'Destroy', film, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Film', new_film_path %>

app/views/films/index.html.erb
<div class="page-header">
<%= link_to new_film_path, :class => 'btn btn-primary' do %>
    <i class="icon-plus icon-white"></i>
    Añadir Película
<%end%>

<h1>Gestión de Películas</h1>
</div>
<table class="tabla" style="width: 100%">
  <tr>
    <th>Título</th>
    <th>Año</th>
    <th>Duración</th>
    <th>Precio de Alquiler</th>
    <th>Precio de Compra</th>
    <th>Sinopsis</th>
    <th></th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @films.each do |film| %>
  <tr>
    <td><%= link_to film.title, film  %></td>
    <td><%= film.year %></td>
    <td><%= film.time %></td>
    <td><%= film.rental_price %></td>
    <td><%= film.buy_price %></td>
    <td><%= film.sinopsis %></td>
    <td class="btn-tabla"><%= link_to 'Alquileres/Compras', film_rents_path(film.id), :class => "btn btn-mini btn-blue" %></td>
    <td class="btn-tabla"><%= link_to 'Mostrar', film, :class => "btn btn-mini btn-blue" %></td>
    <td class="btn-tabla"><%= link_to 'Editar', edit_film_path(film), :class => "btn btn-mini btn-blue" %></td>
    <td class="btn-tabla"><%= link_to 'Eliminar', film, confirm: '¿Seguro que desea eliminar la película?', method: :delete, :class => "btn btn-mini btn-blue" %></td>
  </tr>
<% end %>
</table>

<br />

app/views/films/new.html.erb
<h1>New film</h1>

<%= render 'form' %>

<%= link_to 'Back', films_path %>

app/views/films/show.html.erb
<div class="row">
  <p id="notice"><%= notice %></p>
  <div class="span3" id="MovieInfo">
    <div class="ImageContainer"><%= image_tag @film.poster.url %></div>
    <div class="informacion" id="TableInfoMovie">
      <ul>
        <li> Año: <%= @film.year %></li>
        <li> Duración: <%= @film.time %> minutos</li>
        <li> Sinopsis:</li>
        <li><pre><%= @film.sinopsis %></pre></li>
      </ul>
    </div>
  </div>
    <div class="span7" id="MovieContainer">
      <h1 id="titulo_pelicula">
        <%= @film.title %>
      </h1>
      <% if current_user and current_user.films.include?(@film) %>
        <% f=current_user.rents.find_by_film_id(@film)%>
        <% if f.rent %>
          <%if f.end_date >= Time.current() %>
            <%=render '/films/film_sin_anuncios'%>
          <%else%>
            <%=render '/films/film_con_anuncion'%>
          <%end%>
        <%else%>
          <%=render 'film_sin_anuncios'%>
        <%end%>
      <%else%>
        <%=render '/films/film_con_anuncion'%>
      <%end%>

      <div class="comments">
        <%= render "comments/comment" %>
        <%if current_user %>
          <%= render "comments/form" %>
        <%end%>
      </div>
    </div>

    <div id="GetMovie">
      <%if current_user and current_user.films.include?(@film) %>
        <% f=current_user.rents.find_by_film_id(@film)%>
        <%if f.rent%>
          <%if f.end_date >= Time.current() %>
            <%=render 'alquilada'%>
          <%else%>
            <%=render 'sincomprar'%>
          <%end%>
        <%else%>
          <%=render 'comprada'%>
        <%end%>
      <%else%>
        <%=render 'sincomprar'%>
      <%end%>

    </div>
    <!-- <div>
      <%= link_to 'Edit', edit_film_path(@film) %> |
      <%= link_to 'Back', films_path %>
    </div> -->
  </div>
</div>