config/routes.rb
Videoclub::Application.routes.draw do
   match "mycomments" => "users#mycomments"
   match "myrents" => "users#myrents"
   match "search" => "films#finder"

  resources :commercials

   authenticated :user do
      root :to =>"home#index"
   end

   root :to =>"home#index"
   devise_for :users

   resources :users, :only => [:index, :destroy] do
      resources :rents, :only => [:index]
      resources :comments, :only => [:index]
   end

   resources :films do
      resources :comments
      resources :rents, :only => [:index, :create, :new]
   end

   resources :comments, :only => [:edit, :destroy]
   resources :rents, :except => [:create, :new]
   resources :groups

   resources :paypals
   resources :cards

end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :comments
  has_many :rents
  has_many :films, :through => :rents
  has_many :cards, :dependent => :destroy
  has_many :suscriptions, :dependent => :destroy
  has_many :groups, :through => :suscriptions
  before_create :asigna_grupo_defecto

  attr_accessor :login
  validates_presence_of :username
  validates_uniqueness_of :username
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :authentication_keys => [:login]

  # Setup accessible (or protected) attributes for your model
  attr_accessible :username,:email, :password, :password_confirmation, :remember_me, :login
  # attr_accessible :title, :body


 def self.find_first_by_auth_conditions(warden_conditions)
    conditions = warden_conditions.dup
    if login = conditions.delete(:login)
      where(conditions).where(["lower(username) = :value OR lower(email) = :value", { :value => login.downcase }]).first
    else
      where(conditions).first
    end
  end
 def asigna_grupo_defecto
	self.groups << Group.find_by_name('base')
 end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :authenticate_user!
  before_filter :is_admin, :except => [:mycomments, :myrents]
  def index
      @users = User.all
  end

  def show
      @user = User.find(params[:id])
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/menu/_admin_menu.html.erb
<% if user_signed_in? and current_user.groups.find_by_name('admin') %>
      <%= link_to "Gestion Usuarios",users_path,class: "btn btn-large btn-primary" %>
      <%= link_to "Gestion Peliculas",films_path,class: "btn btn-large btn-primary" %>
      <%= link_to "Gestion Commercials",commercials_path,class: "btn btn-large btn-primary" %>
      <%= link_to "Gestion Alquileres/Compras",rents_path,class: "btn btn-large btn-primary" %>
   </div>
<% end %>

app/views/users/menu/_login_items.html.erb
<% if user_signed_in? %>
  <li>
  <%= link_to('Logout', destroy_user_session_path, :method => :delete , class: "btn btn-mini btn-blue") %>        
  </li>
<% else %>
  <li>
  <%= link_to('Login', new_user_session_path , class: "btn btn-mini btn-blue")  %>  
  </li>
<% end %>

app/views/users/menu/_registration_items.html.erb
<% if user_signed_in? %>
  <li>
  <%= link_to('Edit Profile', edit_user_registration_path, class: "btn btn-mini btn-blue") %>
  </li>
<% else %>
  <li>
  <%= link_to('Register', new_user_registration_path, class: "btn btn-mini btn-blue")  %>
  </li>
<% end %>

app/views/users/menu/_user_name.html.erb
<% if user_signed_in? %>
  <ul>
  <li class="user_name">
  <%= current_user.email %>
  </li></ul>
<% end %>